### ISSUE TITLE
Harvest call reverts

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin-dollar#351]
We have prop18 approved for execution for calling harvest() on the vault.

I tried to execute it but ran into a couple of new issues:
  1. It looks like now the scripts/governor/execute.js script is not able to estimate gas (it used to work)
```
francks-mbp:contracts franck$ node scripts/governor/execute.js --propId=18 --doIt=true
Config:
{ doIt: true, govAddr: undefined, propId: '18' }
Total number of proposals: 19
Current proposal state: 1
getActions(18) [
  [ '0x277e80f3E14E7fB3fc40A9d6184088e0241034bD' ],
  [ BigNumber { _hex: '0x00', _isBigNumber: true } ],
  [ 'harvest()' ],
  [ '0x' ],
  targets: [ '0x277e80f3E14E7fB3fc40A9d6184088e0241034bD' ],
  signatures: [ 'harvest()' ],
  calldatas: [ '0x' ]
]
Sending tx to execute proposal 18...
Gas price (gwei): Regular=16.5 Premium=18.48
Error: execution reverted: Timelock::executeTransaction: Transaction execution reverted.
    at HttpProvider.send (/Users/franck/src/origin-dollar/contracts/node_modules/@nomiclabs/buidler/src/internal/core/providers/http.ts:36:34)
    at /Users/franck/src/origin-dollar/contracts/node_modules/@nomiclabs/buidler/src/internal/core/providers/accounts.ts:149:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 3,
  data: '0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000003d54696d656c6f636b3a3a657865637574655472616e73616374696f6e3a205472616e73616374696f6e20657865637574696f6e2072657665727465642e000000'
}
``` 
  2. Setting a gasLimit manually works but then the transaction reverts
```
node scripts/governor/execute.js --propId=18 --gasLimit=3000000 --doIt=true
```
Reverted tx: https://etherscan.io/tx/0x66736902ca5149a7099c28ffeb8e1fa4dc15310c57771e738d3fb6cdfb6f72b9

Based on our debug tool http://analytics.ousd.com/tx/debug/0x66736902ca5149a7099c28ffeb8e1fa4dc15310c57771e738d3fb6cdfb6f72b9 , it looks like we are failing in collectRewardToken() on the Aave strategy.
I think we are missing a conditional in the harvest() method to make sure ```rewardTokenAddress != address(0)``` since the Aave strategy does not have a reward token?

**Comment by franckc** [comment]
CC @tomlinton @DanielVF

**Comment by franckc** [comment]
Fixes to auto-harvest deployed to mainnet.
